### ISSUE TITLE
Exponential distribution parsing error

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/pix-framework#3]
`pix-framework` serializes the exponential distribution with 3 parameters, https://github.com/AutomatedProcessImprovement/pix-framework/blob/main/src/pix_framework/statistics/distribution.py#L142C8-L147

`prosimos` assumes 4 parameters, https://github.com/AutomatedProcessImprovement/Prosimos/blob/main/prosimos/probability_distributions.py#L132

@ira-halenok, could you please help with this issue either by modifying `pix-framework` or `prosimos`?

## Test case

Test case input files: [Archive.zip](https://github.com/AutomatedProcessImprovement/pix-framework/files/11746836/Archive.zip)

Execution:
```
prosimos start-simulation --bpmn_path PurchasingExample.bpmn --json_path PurchasingExample.json  --total_cases 97 --log_out_path ./simulated_log.csv
```

Fails with:

```
  File "venv/lib/python3.9/site-packages/prosimos/probability_distributions.py", line 132, in evaluate_distribution_function
    loc = params[-4]
IndexError: list index out of range
```

**Comment by ira-halenok** [comment]
@iharsuvorau yes, I am aware of this issue. Thanks for creating an issue.
`Prosimos` will be updated to support 3 parameters only at the moment. 
I already have those changes in the branch. I plan to merge them tomorrow if my testing goes smooth.

**Comment by ira-halenok** [comment]
@iharsuvorau Just letting you know that this issue was resolved in [this release](https://github.com/AutomatedProcessImprovement/Prosimos/releases/tag/1.2.6). I have tested the provided example and it is executed successfully now.
